#!/usr/bin/env python3
"""LaTeX table of the convergence / error estimates, plus error macros."""
import json
import os
import numpy as np

from paper_dir import PAPER as OUT

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

conv = json.load(open(os.path.join(DATA, "convergence.json")))
orb = json.load(open(os.path.join(DATA, "orbit_counts.json")))["summary"]
cat = json.load(open(os.path.join(DATA, "catalog.json")))

rows = []
for c in sorted(conv, key=lambda c: c["name"]):
    o = orb.get(c["name"], {})
    n = o.get("orbits")
    d = c.get("dphi_max_inspiral")
    if d is None:
        continue
    rel = d / (4 * np.pi * n) if n else None
    rows.append((c["name"], c["lo"], c["hi"], n, d, rel, c.get("dphi_extrap")))

lines = []
for name, lo, hi, n, d, rel, dx in rows:
    lines.append(" & ".join([
        name.replace("_", "\\_"),
        f"{lo}$\\to${hi}",
        f"{n:.1f}" if n else "--",
        f"{d:.2e}",
        f"{rel:.1e}" if rel else "--",
    ]) + r" \\")

tbl = r"""% autogenerated by scripts/make_convergence_table.py -- do not edit
\begin{ruledtabular}
\begin{tabular}{lcrcc}
Name & Levs & $N_{\rm orb}$ & $\max|\Delta\phi_{22}|$ [rad] &
$\max|\Delta\phi_{22}| / \phi_{\rm orb}$ \\
\hline
""" + "\n".join(lines) + r"""
\end{tabular}
\end{ruledtabular}
"""
open(os.path.join(OUT, "table_convergence.tex"), "w").write(tbl)
print("wrote table_convergence.tex", len(lines), "rows")

ds = [r[4] for r in rows]
rels = [r[5] for r in rows if r[5]]
short = [r for r in rows if r[3] and r[3] < 25]
longr = [r for r in rows if r[3] and r[3] >= 25]

macros = {
    "NConv": f"{len(rows)}",
    "DphiMin": f"{min(ds):.0e}".replace("e-0", r"\times10^{-") + "}",
    "DphiMedian": f"{np.median(ds):.3f}",
    "DphiMax": f"{max(ds):.1f}",
    "DphiShortMax": f"{max(r[4] for r in short):.3f}" if short else "--",
    "DphiLongMin": f"{min(r[4] for r in longr):.2f}" if longr else "--",
    "RelPhaseMedian": f"{np.median(rels):.1e}" if rels else "--",
    "NConvShort": f"{len(short)}",
    "NConvLong": f"{len(longr)}",
}

# ------------------------------------------------ what a CE-era analysis needs
# For a phase-dominated difference the mismatch is MM ~ dphi^2 / 2, so a target
# mismatch corresponds to dphi = sqrt(2 MM).  The Lindblom-Owen-Brown
# indistinguishability condition MM < D/(2 rho^2) is the same relation, giving
# the familiar dphi < sqrt(D)/rho.
#
# The per-level improvement factor cannot be measured from phase differences:
# no simulation in the catalogue has two *consecutive* level pairs (the Lev2
# product of EccContPrecDiff001 was never generated).  We therefore bracket it
# by the two things we can defend -- the AMR tolerance ladder, which tightens
# by 4 per level by construction, and the observed constraint improvement per
# level for the long runs.
try:
    dist = json.load(open(os.path.join(DATA, "distinguishability.json")))
    con = json.load(open(os.path.join(DATA, "constraints.json")))
    rec = next(r for r in rows if r[0] == "EccPrecDiff002")
    dphi_now = rec[4]
    rho_ce = dist["EccPrecDiff002"]["snr"]["CE"]
    D_intrinsic = 8.0

    ratios = [v["ratio_lo_hi"] for v in con.values() if "ratio_lo_hi" in v
              and max(v[k]["t_end"] for k in v if k.isdigit()) > 10000]
    r_con = float(np.median(ratios))

    # The per-level improvement factor is bracketed by the two consecutive
    # ratios of EccPrecDiff001 -- the ONLY catalogue simulation with three
    # levels of data, and, since it shares its initial data bit-for-bit with
    # EccPrecDiff002, the most relevant possible proxy for the record run.
    # Each ratio is taken on the time window the two levels share, because the
    # levels stop at different times and the constraints grow towards merger.
    harv = json.load(open(os.path.join(DATA, "constraints_harvest.json")))

    def med_on_shared(lo, hi):
        a = np.asarray(harv[f"EccPrecDiff001|Ecc0|Lev{lo}"]["norm_series"],
                       dtype=float)
        b = np.asarray(harv[f"EccPrecDiff001|Ecc0|Lev{hi}"]["norm_series"],
                       dtype=float)
        t0 = max(a[0, 0], b[0, 0]) + 200.0
        t1 = min(a[-1, 0], b[-1, 0])
        ml = np.median(a[(a[:, 0] >= t0) & (a[:, 0] <= t1), 1])
        mh = np.median(b[(b[:, 0] >= t0) & (b[:, 0] <= t1), 1])
        return float(ml / mh)

    f_meas = sorted(med_on_shared(lo, hi) for lo, hi in ((2, 3), (3, 4)))

    tol_ce = np.sqrt(D_intrinsic) / rho_ce
    levs = [3 + int(np.ceil(np.log(dphi_now / tol_ce) / np.log(f)))
            for f in f_meas]
    macros.update({
        "PerLevelMeasLo": f"{f_meas[0]:.1f}",
        "PerLevelMeasHi": f"{f_meas[-1]:.1f}",
        "PerLevelThreeLevRun": "EccPrecDiff001",
    })
    macros.update({
        "CESNRRef": f"{rho_ce:.0f}",
        "CEDphiTol": f"{tol_ce:.1e}".replace("e-0", r"\times10^{-") + "}",
        "CEDphiFactor": f"{dphi_now / tol_ce:.0f}",
        "PerLevelCon": f"{r_con:.1f}",
        "LevCEMin": f"{min(levs)}",
        "LevCEMax": f"{max(levs)}",
        "DphiNowLong": f"{dphi_now:.1f}",
        "DIntrinsic": f"{D_intrinsic:.0f}",
    })

    # Per-detector forecast table.  A+ is included to show how the requirement
    # scales with signal-to-noise ratio rather than with anything intrinsic to
    # the simulation: it needs ~2 fewer levels than CE, but is not met either.
    trows = []
    for det in ("A+", "ET", "CE"):
        rho = dist["EccPrecDiff002"]["snr"].get(det)
        if not rho:
            continue
        tol = np.sqrt(D_intrinsic) / rho
        ns = sorted(np.log(dphi_now / tol) / np.log(f) for f in f_meas)
        if ns[-1] <= 0:                      # already satisfied at Lev3
            need = r"already met"
        else:
            lo = 3 + int(np.ceil(max(ns[0], 0)))
            hi = 3 + int(np.ceil(ns[-1]))
            need = (rf"\texttt{{Lev{lo}}}" if lo == hi
                    else rf"\texttt{{Lev{lo}}}--\texttt{{Lev{hi}}}")
        label = {"A+": r"A$+$", "ET": "ET", "CE": "CE"}[det]
        mant, ex = f"{tol:.1e}".split("e")
        trows.append(rf"{label} & {rho:.0f} & ${mant}\times10^{{{int(ex)}}}$ "
                     rf"& {dphi_now / tol:.0f} & {need} \\")
    tbl_ce = (
        "% autogenerated by scripts/make_convergence_table.py -- do not edit\n"
        r"\begin{ruledtabular}" "\n" r"\begin{tabular}{lcccc}" "\n"
        r"Detector & $\rho$ & $\Delta\phi_{\rm tol}$ (rad) &"
        r" $\Delta\phi_{23}/\Delta\phi_{\rm tol}$ & Required \\" "\n"
        r"\hline" "\n" + "\n".join(trows) + "\n"
        r"\end{tabular}" "\n" r"\end{ruledtabular}" "\n")
    open(os.path.join(OUT, "table_ce_forecast.tex"), "w").write(tbl_ce)
    print(f"wrote table_ce_forecast.tex ({len(trows)} rows)")
except (KeyError, StopIteration, FileNotFoundError, ValueError) as e:
    print(f"  [skip CE-requirement macros] {type(e).__name__}: {e}")
with open(os.path.join(OUT, "macros_conv.tex"), "w") as f:
    f.write("% autogenerated by scripts/make_convergence_table.py\n")
    for k, v in macros.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print("wrote macros_conv.tex")
for k, v in macros.items():
    print(f"   {k:<16} {v}")
print()
print(f"{'name':<22}{'levs':>7}{'orbits':>8}{'dphi[rad]':>12}{'dphi/phi_orb':>14}")
for name, lo, hi, n, d, rel, dx in rows:
    print(f"{name:<22}{lo}->{hi:<4}{(n or 0):>8.1f}{d:>12.2e}"
          f"{(rel if rel else 0):>14.2e}")
