#!/usr/bin/env python3
"""Emit table_firstlaw_frame.tex -- the first law in both frames.

Reads data/first_law_frames.json (written by first_law_frames.py) and tabulates
the orbit-averaged residue in the co-precessing and inertial frames side by
side, sorted so that the aligned-spin null test (ratio = 1) sits together at
the top and the precessing runs follow in order of eccentricity.
"""
import os
import json

from paper_dir import PAPER

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

HEADER = "% autogenerated by scripts/make_firstlaw_frame_table.py -- do not edit\n"


def sci(x, n=1):
    from math import floor, log10
    ex = int(floor(log10(abs(x))))
    return rf"${x / 10 ** ex:.{n}f} \times 10^{{{ex}}}$"


def main():
    frames = json.load(open(os.path.join(DATA, "first_law_frames.json")))
    surv = {r["name"]: r for r in
            json.load(open(os.path.join(DATA, "coprec_survey.json")))}

    def key(kv):
        k, v = kv
        return (v["precessing"], v["ecc"] if v["ecc"] else -1.0, k)

    rows = sorted(frames.items(), key=key)

    L = [HEADER]
    L.append(r"\begin{tabular}{lcccc}")
    L.append(r"\hline\hline")
    L.append(r"Simulation & $e$ & $\beta$ (deg) & $|R|_{\rm cp}$ &"
             r" $|R|_{\rm in}/|R|_{\rm cp}$ \\")
    L.append(r"\hline")
    prec_started = False
    for k, v in rows:
        if v["precessing"] and not prec_started:
            L.append(r"\hline")
            prec_started = True
        b = surv.get(k, {}).get("beta_med")
        ecc = f"{v['ecc']:.3f}" if v["ecc"] else r"---"
        bs = f"{b:.1f}" if (b is not None and b > 1e-3) else r"$<10^{-3}$"
        L.append(rf"\texttt{{{k.replace('_', r'\_')}}} & {ecc} & {bs} & "
                 rf"{sci(v['R_cp'])} & {v['ratio']:.2f} \\")
    L.append(r"\hline\hline")
    L.append(r"\end{tabular}")

    out = os.path.join(PAPER, "table_firstlaw_frame.tex")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"wrote {out} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
