#!/usr/bin/env python3
"""Generate the LaTeX catalogue tables and the \newcommand macro file."""
import json
import os
import numpy as np

from paper_dir import PAPER as OUT

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

cat = json.load(open(os.path.join(DATA, "catalog.json")))
tim = json.load(open(os.path.join(DATA, "timings.json")))
orb = json.load(open(os.path.join(DATA, "orbit_counts.json")))["summary"]

# The website tables report "Ncycles", which is the number of gravitational-wave
# cycles of the (2,2) mode.  The number of ORBITS is half that.  Where we have
# the waveform we use the directly measured value; otherwise we fall back to the
# tabulated cycle count divided by two.
def orbits_of(e):
    o = orb.get(e["name"])
    if o:
        return o["orbits"], o["gw_cycles"], True
    nc = e.get("ncycles_max")
    if nc:
        return nc / 2.0, nc, False
    return None, None, False

bysim = {}
for r in tim:
    bysim.setdefault(r["sim"], []).append(r)


def fv(v, fmt="{:.3f}"):
    return "--" if v is None else fmt.format(v)


def vec(v):
    if not v:
        return "--"
    return "(" + ",\\,".join(f"{x:+.2f}" for x in v) + ")"


# ------------------------------------------------------------- main table
lines = []
order = sorted(cat.values(), key=lambda e: (e["series"], e["name"]))
for e in order:
    n = e["name"]
    rr = bysim.get(n, [])
    levs = sorted({r["lev"] for r in rr})
    cpu = max((r["cpu_h"] for r in rr), default=None)
    tf = max((r["t_final_M"] for r in rr), default=None)
    lines.append(
        " & ".join([
            n.replace("_", "\\_"),
            fv(e.get("q"), "{:.2f}"),
            vec(e.get("chiA")),
            vec(e.get("chiB")),
            fv(e.get("ecc"), "{:.2f}"),
            fv(e.get("D0"), "{:.1f}"),
            fv(e.get("chi_eff"), "{:+.2f}"),
            fv(e.get("chi_p"), "{:.2f}"),
            fv(orbits_of(e)[0], "{:.1f}"),
            fv(orbits_of(e)[1], "{:.0f}"),
            fv(tf, "{:.0f}"),
            ",".join(str(l) for l in levs) if levs else "--",
            fv(cpu / 1000 if cpu else None, "{:.1f}"),
        ]) + r" \\"
    )

tbl = r"""% autogenerated by scripts/make_tables.py -- do not edit
\begin{ruledtabular}
\begin{tabular}{lccccccccccrr}
Name & $q$ & $\vec{\chi}_1$ & $\vec{\chi}_2$ & $e_0$ & $D_0/M$ &
$\chi_{\rm eff}$ & $\chi_{\rm p}$ & $N_{\rm orb}$ & $N_{\rm cyc}$ &
$t_{\rm f}/M$ & Levs & kCPU-h \\
\hline
""" + "\n".join(lines) + r"""
\end{tabular}
\end{ruledtabular}
"""
open(os.path.join(OUT, "table_catalog.tex"), "w").write(tbl)
print("wrote table_catalog.tex", len(lines), "rows")

# ------------------------------------------------------------- macros
nsim = len(cat)
nprec = sum(1 for e in cat.values() if e["precessing"])
necc = sum(1 for e in cat.values() if (e.get("ecc") or 0) > 1e-3)
nboth = sum(1 for e in cat.values() if e["precessing"] and (e.get("ecc") or 0) > 1e-3)
ncomp = sum(1 for e in cat.values() if e.get("n_completed", 0) > 0)
tot_cpu = sum(r["cpu_h"] for r in tim)
tot_wall = sum(r["wall_h"] for r in tim)
nruns = len(tim)
# EccPrecDiff001 and 002 are the same physical configuration and are within
# 0.5 orbit of each other; 002 is the showcase run (both levels completed and
# the better converged of the pair), so pin the macros to it for consistency
# with the figures, and report the pair in the text.
_ranked = sorted((e for e in cat.values() if orbits_of(e)[0]),
                 key=lambda e: -orbits_of(e)[0])
longest = next((e for e in _ranked if e["name"] == "EccPrecDiff002"), _ranked[0])
lt = [r for r in tim if r["sim"] == longest["name"]]
lt_wall = max((r["wall_h"] for r in lt), default=0)
lt_tf = max((r["t_final_M"] for r in lt), default=0)
lt_cpu = max((r["cpu_h"] for r in lt), default=0)
speeds = [r["speed_M_per_h"] for r in tim if r.get("speed_M_per_h")]
qs = [e["q"] for e in cat.values() if e.get("q")]
eccs = [e["ecc"] for e in cat.values() if e.get("ecc") is not None]

macros = {
    "Nsim": f"{nsim}",
    "Nprec": f"{nprec}",
    "Necc": f"{necc}",
    "Nboth": f"{nboth}",
    "Nruns": f"{nruns}",
    "TotCPU": f"{tot_cpu/1e6:.2f}",
    "TotWall": f"{tot_wall/1e3:.1f}",
    "LongName": longest["name"],
    "LongOrbits": f"{orbits_of(longest)[0]:.0f}",
    "LongCycles": f"{orbits_of(longest)[1]:.0f}",
    "MaxOrbits": f"{max(orbits_of(e)[0] for e in cat.values() if orbits_of(e)[0]):.0f}",
    "LongTf": f"{lt_tf/1000:.1f}",
    "LongWall": f"{lt_wall:.0f}",
    "LongCPU": f"{lt_cpu/1000:.0f}",
    "LongDays": f"{lt_wall/24:.0f}",
    "LongSpeed": f"{lt_tf/lt_wall:.0f}" if lt_wall else "--",
    "Qmin": f"{min(qs):.0f}",
    "Qmax": f"{max(qs):.1f}",
    "Eccmax": f"{max(eccs):.2f}",
    # largest initial dimensionless spin magnitude over both holes; quoted in
    # the abstract, so it must come from the data rather than be hand-typed
    "Chimax": f"{max(max(np.linalg.norm(e[k]) for k in ('chiA', 'chiB') if e.get(k)) for e in cat.values() if e.get('chiA') or e.get('chiB')):.1f}",
    "SpeedMax": f"{max(speeds):.0f}",
}
with open(os.path.join(OUT, "macros.tex"), "w") as f:
    f.write("% autogenerated by scripts/make_tables.py -- do not edit\n")
    for k, v in macros.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print("wrote macros.tex")
for k, v in macros.items():
    print(f"   {k:<12} {v}")
