#!/usr/bin/env python3
"""LaTeX table of the convergence / error estimates, plus error macros."""
import json
import os
import numpy as np

from paper_dir import PAPER as OUT

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")

conv = json.load(open(os.path.join(DATA, "convergence.json")))
orb = json.load(open(os.path.join(DATA, "orbit_counts.json")))["summary"]
cat = json.load(open(os.path.join(DATA, "catalog.json")))

rows = []
for c in sorted(conv, key=lambda c: c["name"]):
    o = orb.get(c["name"], {})
    n = o.get("orbits")
    d = c.get("dphi_max_inspiral")
    if d is None:
        continue
    rel = d / (4 * np.pi * n) if n else None
    rows.append((c["name"], c["lo"], c["hi"], n, d, rel, c.get("dphi_extrap")))

lines = []
for name, lo, hi, n, d, rel, dx in rows:
    lines.append(" & ".join([
        name.replace("_", "\\_"),
        f"{lo}$\\to${hi}",
        f"{n:.1f}" if n else "--",
        f"{d:.2e}",
        f"{rel:.1e}" if rel else "--",
    ]) + r" \\")

tbl = r"""% autogenerated by scripts/make_convergence_table.py -- do not edit
\begin{ruledtabular}
\begin{tabular}{lcrcc}
Name & Levs & $N_{\rm orb}$ & $\max|\Delta\phi_{22}|$ [rad] &
$\max|\Delta\phi_{22}| / \phi_{\rm orb}$ \\
\hline
""" + "\n".join(lines) + r"""
\end{tabular}
\end{ruledtabular}
"""
open(os.path.join(OUT, "table_convergence.tex"), "w").write(tbl)
print("wrote table_convergence.tex", len(lines), "rows")

ds = [r[4] for r in rows]
rels = [r[5] for r in rows if r[5]]
short = [r for r in rows if r[3] and r[3] < 25]
longr = [r for r in rows if r[3] and r[3] >= 25]

macros = {
    "NConv": f"{len(rows)}",
    "DphiMin": f"{min(ds):.0e}".replace("e-0", r"\times10^{-") + "}",
    "DphiMedian": f"{np.median(ds):.3f}",
    "DphiMax": f"{max(ds):.1f}",
    "DphiShortMax": f"{max(r[4] for r in short):.3f}" if short else "--",
    "DphiLongMin": f"{min(r[4] for r in longr):.2f}" if longr else "--",
    "RelPhaseMedian": f"{np.median(rels):.1e}" if rels else "--",
    "NConvShort": f"{len(short)}",
    "NConvLong": f"{len(longr)}",
}
with open(os.path.join(OUT, "macros_conv.tex"), "w") as f:
    f.write("% autogenerated by scripts/make_convergence_table.py\n")
    for k, v in macros.items():
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print("wrote macros_conv.tex")
for k, v in macros.items():
    print(f"   {k:<16} {v}")
print()
print(f"{'name':<22}{'levs':>7}{'orbits':>8}{'dphi[rad]':>12}{'dphi/phi_orb':>14}")
for name, lo, hi, n, d, rel, dx in rows:
    print(f"{name:<22}{lo}->{hi:<4}{(n or 0):>8.1f}{d:>12.2e}"
          f"{(rel if rel else 0):>14.2e}")
