#!/usr/bin/env python3
"""Longest simultaneously eccentric and precessing run in the SXS catalogue.

The paper claims \\LongName{} is the longest simultaneously eccentric and
precessing BBH evolution performed to date.  That is a claim about the
literature, so it needs a checkable reference point rather than an assertion:
this script queries the public SXS catalogue and emits the longest SXS run that
is both eccentric and precessing, which is the number the text quotes.

`reference_eccentricity` is sometimes a string ("<1e-5"), so it is coerced.
Precession is measured by the larger of the two reference perpendicular spins.

The thresholds are deliberately loose (e > 0.01, chi_perp > 0.01): the answer
is insensitive to them, and a loose cut is the conservative choice for a claim
of this form, since it lets in more potential counterexamples.

Writes macros_sxs.tex into the paper repo.  Requires the `sxs` package and its
cached catalogue metadata (~/.cache/sxs).
"""
import os

from paper_dir import PAPER as OUT

ECC_MIN = 0.01
CHIP_MIN = 0.01


def num(x):
    try:
        if isinstance(x, str):
            x = x.strip().lstrip("<>~")
        return float(x)
    except (TypeError, ValueError):
        return None


def main():
    import sxs

    sims = sxs.load("simulations")
    tag = getattr(sims, "tag", None) or "v3.0.0"

    rows = []
    for k in sims:
        m = sims[k]
        n = num(m.get("number_of_orbits"))
        e = num(m.get("reference_eccentricity"))
        if n is None or e is None:
            continue
        p = max(num(m.get("reference_chi1_perp")) or 0.0,
                num(m.get("reference_chi2_perp")) or 0.0)
        rows.append((k, n, e, p))

    both = [r for r in rows if r[2] > ECC_MIN and r[3] > CHIP_MIN]
    both.sort(key=lambda r: -r[1])
    if not both:
        print("  [skip] no eccentric+precessing SXS runs found")
        return
    k, n, e, p = both[0]

    macros = {
        "SXSCatalogTag": str(tag).replace("_", r"\_"),
        "SXSNTotal": f"{len(rows)}",
        "SXSNEccPrec": f"{len(both)}",
        "SXSLongestEccPrec": k.replace(":", r":\allowbreak "),
        "SXSLongestEccPrecName": k,
        "SXSLongestEccPrecOrbits": f"{n:.1f}",
        "SXSLongestEccPrecEcc": f"{e:.2f}",
        "SXSLongestEccPrecChiP": f"{p:.2f}",
        "SXSEccCut": f"{ECC_MIN}",
        "SXSChiPCut": f"{CHIP_MIN}",
    }
    with open(os.path.join(OUT, "macros_sxs.tex"), "w") as f:
        f.write("% autogenerated by scripts/sxs_comparison.py -- do not edit\n")
        for kk, vv in macros.items():
            f.write("\\newcommand{\\%s}{%s}\n" % (kk, vv))
    print("wrote macros_sxs.tex")
    for kk, vv in macros.items():
        print(f"   {kk:26} {vv}")
    print(f"\n  top 5 eccentric+precessing SXS runs by orbit count:")
    for k, n, e, p in both[:5]:
        print(f"    {k:18s} {n:7.1f} orbits  e={e:.3f}  chi_perp={p:.2f}")


if __name__ == "__main__":
    main()
